name: Release on Tag

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'  # Matches semantic version tags like v1.2.3

permissions:
  contents: write  # Required for updating branches

jobs:
  semantic-release:
    uses: /Gergo3/nvim-docker-workflows/.github/workflows/semver-release.yml@master
    secrets:
      inherit

