name: Reusable CI/CD Workflow

on:
  workflow_call:
    secrets:
      IMAGE_NAME:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      is-tag: ${{ steps.detect.outputs.is-tag }}
      tag: ${{ steps.detect.outputs.tag }}
      is-valid-semver: ${{ steps.detect.outputs.is-valid-semver }}
    steps:
      - name: Detect context
        id: detect
        run: |
          REF="${GITHUB_REF}"
          NAME="${GITHUB_REF_NAME}"
          echo "GITHUB_REF=$REF"
          echo "GITHUB_REF_NAME=$NAME"

          if [[ "$REF" == refs/tags/* ]]; then
            echo "is-tag=true" >> $GITHUB_OUTPUT
            if [[ "$NAME" =~ ^v[0-9]+\.[0-9]+(\.[0-9]+)?$ ]]; then
              echo "is-valid-semver=true" >> $GITHUB_OUTPUT
              echo "tag=$NAME" >> $GITHUB_OUTPUT
            else
              echo "is-valid-semver=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "is-tag=false" >> $GITHUB_OUTPUT
          fi

          # Check if this is the master branch
          if [[ "$REF" == refs/heads/master ]]; then
            echo "is-master=true" >> $GITHUB_OUTPUT
          else
            echo "is-master=false" >> $GITHUB_OUTPUT
          fi

  # 🧱 Build on master branch
  build-latest:
    if: ${{ needs.detect.outputs.is-tag == 'false' && needs.detect.outputs.is-master == 'true' }}
    needs: detect
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image-name: ${{ secrets.IMAGE-NAME }}
      image-tags: dev
    secrets: inherit

  # 🚀 Release on valid SemVer tag
  release:
    if: ${{ needs.detect.outputs.is-valid-semver == 'true' }}
    needs: detect
    uses: ./.github/workflows/reusable-semver-release.yml
    with:
      image-name: ${{ secrets.IMAGE-NAME }}
    secrets: inherit

